### ISSUE TITLE
Cover detail article tidak muncul

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#48]
Cover pada detail article tidak muncul . API = https://dev.one.co.id/api/article/[id_article]

![image](https://user-images.githubusercontent.com/40710667/42550435-e5b25048-84fb-11e8-8af7-6d9a0267e074.png)

ini dikarenakan, data cover tidak ada. yang bisa tampil didetail article  adalah cover 2:1 .

contoh punya vemale : 
![image](https://user-images.githubusercontent.com/40710667/42550462-0b55668c-84fc-11e8-890a-3851d6423059.png)

yang betul  ada data cover: 
![image](https://user-images.githubusercontent.com/40710667/42550502-66fbc706-84fc-11e8-8265-18e277d053d1.png)

**Comment by charsme** [comment]
@setiawanYusuf data photos yang dikirim ada yang kurang. Ratio nya pastikan kirim semua yang ada + cover.

**Comment by jeffreymesach** [comment]
thanks
