### ISSUE TITLE
muncul tag [ ] di  body article vemale

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#49]
muncul tag [ ] dengan isi macam2. seperti ini (sepertinya ascii, kecuali [pos_1])

![image](https://user-images.githubusercontent.com/40710667/42610355-5ba14768-85bb-11e8-99d2-6bb57e1509ac.png)

![image](https://user-images.githubusercontent.com/40710667/42610682-e3612708-85bc-11e8-83c5-531bbefa929b.png)

ada lagi [sosmed_578], [bullet]-> ini seperti nya icon point type dot

untuk POS_1 seperti nya ada hubungannya dengan cms  ini 
![image](https://user-images.githubusercontent.com/40710667/42610741-1744b03a-85bd-11e8-8c72-2a09373b7d2b.png)

**Comment by setiawanYusuf** [comment]
@jeffreymesach  @charsme 

Bisa diperiksa lagi ya, untuk masalah tag [].

Terima kasih
