### ISSUE TITLE
time tidak muncul

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#50]
date sudah muncul ,  time nya  belum muncul
![image](https://user-images.githubusercontent.com/40710667/42610848-9911ebf0-85bd-11e8-9f1b-9fa53a7ec757.png)

**Comment by setiawanYusuf** [comment]
@jeffreymesach @charsme 

Bisa diperiksa juga untuk masalah time date ini ya.

Terima kasih

**Comment by jeffreymesach** [comment]
thanks
