### ISSUE TITLE
Gap pada  akhir article, mungkin disebabkan banyak <br>

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#52]
pada judul artikel : Tak Semua Pertanyaan Bisa Dijawab Cepat, Termasuk Soal Kapan Nikah

![image](https://user-images.githubusercontent.com/40710667/42857563-8dbce0fa-8a74-11e8-8a09-f519d1147cee.png)

bisa disisakan 1 saja jika terdapat lebih dari 1

**Comment by charsme** [comment]
Kalau semacam ini dari editorial sih lebih masuknya. Aku sundulkan ke CM nya saja. Sembari ini aku close.

**Comment by jeffreymesach** [comment]
Pak Charis, untuk CM ini bagian apa ya pak?
waktu lalu saya cek di CMS nya tidak ada br atau nbsp di akhir artikel

**Comment by charsme** [comment]
CM -> Channel Manager. Lead editornya. Sebelumnya aku cek ini karena editor copas dari artikel submisi user. Sehingga banyak enter yang udah di trim, editor yang input ke cms ga ngecek hasil pastenya lebih lanjut.

**Comment by jeffreymesach** [comment]
oke siap pak Charis, coba saya hub i CM nya
terimakasih
