### ISSUE TITLE
Baca Juga didalam artikel dihilangkan

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#53]
Untuk artikel yang mengandung "Baca Juga" beserta linknya mohon bantuannya untuk di hilangkan waktu push ke ONE

![image](https://user-images.githubusercontent.com/40710667/42866138-f15a3d12-8a95-11e8-90e8-a43421c1029d.png)

![image](https://user-images.githubusercontent.com/40710667/42866264-499310f8-8a96-11e8-9a55-09575bcc541e.png)

**Comment by setiawanYusuf** [comment]
@jeffreymesach  

Bisa diperiksa kembali ya, sudah disubmit ulang.

Terima kasih

**Comment by jeffreymesach** [comment]
thanks, solved.
