### ISSUE TITLE
image 9:16 di apps  tidak muncul tapi di cms sudah di input

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#55]
Article judul : Tak Kunjung Menikah Bukan Berarti Tuhan Tidak Mencintai Kalian
image 9:16 di postman :  
![image](https://user-images.githubusercontent.com/40710667/42868533-c454b71e-8a9c-11e8-83ee-eb727a3b9fee.png)

di CMS : 
![image](https://user-images.githubusercontent.com/40710667/42868557-d47a1224-8a9c-11e8-8a48-81a801a7d45d.png)

di apps : 
![image](https://user-images.githubusercontent.com/40710667/42868653-111814ce-8a9d-11e8-8eaf-68b80785b379.png)

**Comment by setiawanYusuf** [comment]
Sudah dikirim ulang, seharusnya sudah muncul gambar 9:16.

Terima kasih

**Comment by jeffreymesach** [comment]
thankyou
