### ISSUE TITLE
[DREAM] Baca (link dan wording) Juga didalam body artikel mohon dihilangkan

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#57]
![image](https://user-images.githubusercontent.com/40710667/43057128-708ced00-8e6a-11e8-91c9-439d7a2c7a76.png)

**Comment by robbyfellaz** [comment]
ini kemarin pake data dummy jadi fitur "Baca Juga" masih ikut ke push, sekarang bisa dicoba lagi

**Comment by charsme** [comment]
@jeffreymesach hasil pengecekan apakah udah sesuai?
