### ISSUE TITLE
[DREAM] image vertical yang  diambil adalah resolusi 720x1280

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#58]
saat ini yang terambil adalah 300x400

dan pada judul :
  "id": 16965,
   "title": "5 Kesalahan yang Biasa Dilakukan Saat Menyamarkan Dark Circle",
 "photo_id": 472700,
                "photo_url": "https://cdns.klimg.com/vemale.com/headline/650x325/2018//2018/07/5-kesalahan-yang-biasa-dilakukan-saat-menyamarkan-dark-circle-portrait-0716.jpg",
                "photo_ratio": "9:16",
                "photo_description": "Dark circle atau area gelap di bawah mata dapat kamu samarkan dengan mudah menggunakan makeup.",
                "photo_information": "Dark Circle/Copyright Shutterstock"

foto nya not found

**Comment by robbyfellaz** [comment]
sudah diganti ke ratio 9:16.

kalo misal foto gak di isi oleh editor apa dibiarkan kosong aja ? apa diganti image lain ?
