### ISSUE TITLE
[BOLA.NET]Muncul character , pada judul : https://www.bola.net/spanyol/agen-benarkan-minat-barcelona-dan-juventus-untuk-ismaila-sarr-5b6a9e-1.html

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#63]
pada judul : https://www.bola.net/spanyol/agen-benarkan-minat-barcelona-dan-juventus-untuk-ismaila-sarr-5b6a9e-1.html

![image](https://user-images.githubusercontent.com/40710667/43179640-28ed5a1c-8ffe-11e8-8994-920db23b5799.png)

**Comment by charsme** [comment]
@jeffreymesach untuk selanjutnya, semacam url bisa diletakkan di body comment nya saja. Biar titlenya ga panjang banget. Judul bisa declarative aja. Buat guidance mungkin semacam ini:

Judul -> What *What is it about* [Bola.net] Karakter ekstra pada Judul
Body -> 
Where *Where it happen*
How *How do you stumble upon the problem*
Why *Why it is a problem*

**Expected result**

Thanks,

**Comment by charsme** [comment]
has

**Comment by jeffreymesach** [comment]
Noted

**Comment by lordhasyim** [comment]
dear
@jeffreymesach 
@charsme 

Sudah di sesuaikan untuk artikel2 berikutnya, kemungkinan ini string hasil copy-paste, sehingga di artikan huruf \r\n\, bukan sebagai penanda _new lines_ , namun sudah dapat ditasi.

Jika sudah sesuai bisa di close.

Thanks.
