### ISSUE TITLE
[BOLA.NET]Penempatan image info

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#68]
Untuk Penempatan  photo information dan photo description bukan diisi dengan synopsis

![image](https://user-images.githubusercontent.com/40710667/43353238-3d60f6dc-925d-11e8-8508-93c6480f15b1.png)

jika saya lihat cms , untuk field photo information , sebaiknya diisi dengan image info
![image](https://user-images.githubusercontent.com/40710667/43353249-7c02a4a8-925d-11e8-965d-98501a2a1c3e.png)

contoh kasus saya ambil dari : id ONE = 19840
Emery Pastikan Tak Ada Perlakuan Istimewa Untuk Pemain Baru Arsenal

**Comment by lordhasyim** [comment]
pak @jeffreymesach 

Bisa di cek lagi untuk artikel artikel yang terbaru pak.

Terimakasih
