### ISSUE TITLE
[BOLA.NET] Muncul '\' pada Title

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#69]
Muncul character \  pada judul 
sepertinya masalah penampilan tanda petik

![image](https://user-images.githubusercontent.com/40710667/43438604-4ce0cb74-94b9-11e8-97b0-70d258765d2b.png)
![image](https://user-images.githubusercontent.com/40710667/43438621-61f162bc-94b9-11e8-8846-a1b9225a7822.png)

**Comment by lordhasyim** [comment]
pak @jeffreymesach 
sudah di sesuaikan pak, bisa di cek untuk artikel artikel terbaru

Terimakasih
