### ISSUE TITLE
[BOLA.NET] Banyak vertical image yang tidak muncul

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#79]
![image](https://user-images.githubusercontent.com/40710667/43815065-f3c6d1c4-9af7-11e8-86ab-42a332315c95.png)

**Comment by lordhasyim** [comment]
issue ini berhubungan dengan issue yang [https://github.com/KLYgarage/onesdk/issues/81](issue).
saat ini sudah ada penyesuaian bahwa jika image portrait kosong/tidak diisi maka tidak akan di push ke oneapp.
