### ISSUE TITLE
  [BOLA.NET] Salah ambil 9:16

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#81]
Bersiap Hadapi Borneo FC, Arema FC Gelar Uji Coba

![image](https://user-images.githubusercontent.com/40710667/43818859-c1600440-9b0a-11e8-872d-cb5caf752eda.png)

**Comment by lordhasyim** [comment]
![screenshot from 2018-08-08 13-50-12](https://user-images.githubusercontent.com/3645452/43820997-13e77002-9b12-11e8-9c66-bcb9b9c77fb4.png)

saya cek sesuai id diatas itu field nya kosong pak, saya cek di db nya memang kosong(tidak diisi oleh editor) pak

Terimakasih

**Comment by jeffreymesach** [comment]
oh? atau dia salah upload? mesti nya kalau 9:16 nya tidak ada =  tidak terisi / kosong

**Comment by jeffreymesach** [comment]
seperti ini tampilan API untuk artikel yang tidak diisi 9:16 nya
![image](https://user-images.githubusercontent.com/40710667/43878497-b0b5cdb8-9bc9-11e8-962c-7121dcc164fb.png)

**Comment by lordhasyim** [comment]
@jeffreymesach 
begini pak, 
itu yang image 9:16 nya tidak di isi pak, jadi kosong

> kenapa kok ada isinya tapi tidak full image url?

karena cara kerja code yg saya gunakan menggunakan default cdn nya kapanlagi di awal kemudian di gabung kan dengan url image yang diisi oleh editor nya. contoh :

> https://cdns.klimg.com/bola.net/ 

digabung dengan 

> url/dari/editor.jpg

hasilnya menjadi

> https://cdns.klimg.com/bola.net/url/dari/editor.jpg

jika image 9:16 nya tidak diisi maka menghasilkan

> https://cdns.klimg.com/bola.net/

cara mengatasi nya bisa dengan diberi default image size, jadi jika editor tidak menambahkan image maka akan ada default image nya.
jika memang mau di beri default image, image size berapa yang digunakan pak?

Terimakasih

**Comment by jeffreymesach** [comment]
begini, jika tidak ada image vertical nya. tidak perlu di push ke ONE. jadi yang tampil nanti image selain 9:16 yaitu 2:1
