### ISSUE TITLE
[DREAM]keluar ASCII

### ISSUE THREAD

**Issue by jeffreymesach** [KLYgarage/onesdk#83]
judul : Sempat Viral! Begini Kabar Pernikahan Alvin &amp;amp; Larissa Sekarang

![image](https://user-images.githubusercontent.com/40710667/43937770-dfd11d76-9c89-11e8-819b-9486e378d41c.png)

di apps

![image](https://user-images.githubusercontent.com/40710667/43937806-20171b9c-9c8a-11e8-923e-4f8cb6eedb3e.png)

**Comment by robbyfellaz** [comment]
@jeffreymesach ini bisa diperiksa kembali. untuk title sudah di convert ke html entity decode

**Comment by jeffreymesach** [comment]
Noted
